require(raster)
require(rgdal)
require(RStoolbox)
require(rasterdiv)
require(rasterVis)
require(ggplot2)
require(gridExtra)
require(viridis)
require(purrr)
setwd("/Users/federicotossani/Asinara/L_image")

raolist<-list.files(pattern="Rao")
asirao<-lapply(raolist, raster)

rao84<-brick("Rao_84.grd")
rao85<-brick("Rao_85.grd")
rao87<-brick("Rao_87.grd")
rao88<-brick("Rao_88.grd")
rao91<-brick("Rao_91.grd")
rao92<-brick("Rao_92.grd")
rao95<-brick("Rao_95.grd")
rao96<-brick("Rao_96.grd")
rao97<-brick("Rao_97.grd")
rao99<-brick("Rao_99.grd")
rao00<-brick("Rao_00.grd")
rao02<-brick("Rao_02.grd")
rao14<-brick("Rao_14.grd")
rao15<-brick("Rao_15.grd")
rao17<-brick("Rao_17.grd")
rao18<-brick("Rao_18.grd")
rao20<-brick("Rao_20.grd")
